-- Lazy document loading (July 2026).
-- Adds two optional text fields to Document so the AI matcher can decide,
-- per client message, which documents to inject into the prompt.
--   description     = owner-written short label ("что это за файл")
--   autoDescription = fallback generated by Haiku 4.5 if description is empty
-- Both nullable so existing rows keep working; matcher falls back to
-- "load everything" for docs where both are null.

ALTER TABLE "Document"
  ADD COLUMN "description"     TEXT,
  ADD COLUMN "autoDescription" TEXT;
